import { IMovieTrending } from "@/types/movies";

export const moviesTrendingMock: Array<IMovieTrending> = [
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [1, 2],
    id: 1,
    original_languages: "en",
    original_title: "Movie 1",
    overview: "",
    popularity: 1234.23,
    poster_path: "",
    release_date: "2023-05-15",
    title: "Movie 1",
    video: true,
    vote_average: 8.0,
    vote_count: 1000,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [2],
    id: 2,
    original_languages: "en",
    original_title: "Movie 2",
    overview: "",
    popularity: 1234.23,
    poster_path: "",
    release_date: "2022-08-10",
    title: "Movie 2",
    video: true,
    vote_average: 6.5,
    vote_count: 1000,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [1],
    id: 3,
    original_languages: "en",
    original_title: "Movie 3",
    overview: "",
    popularity: 1234.23,
    poster_path: "",
    release_date: "2021-12-20",
    title: "Movie 3",
    video: true,
    vote_average: 7.0,
    vote_count: 1000,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [3],
    id: 1,
    original_languages: "en",
    original_title: "Movie 4",
    overview: "",
    popularity: 1234.23,
    poster_path: "",
    release_date: "2020-03-30",
    title: "Movie 4",
    video: true,
    vote_average: 9.0,
    vote_count: 1000,
  },
];

export const filteredMoviesTrendingMock: Array<IMovieTrending> = [
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [1, 2],
    id: 1,
    original_languages: "en",
    original_title: "Movie 1",
    overview: "",
    popularity: 1234.23,
    poster_path: "",
    release_date: "2023-05-15",
    title: "Movie 1",
    video: true,
    vote_average: 8.0,
    vote_count: 1000,
  },
  {
    adult: false,
    backdrop_path: "",
    genre_ids: [1],
    id: 3,
    original_languages: "en",
    original_title: "Movie 3",
    overview: "",
    popularity: 1234.23,
    poster_path: "",
    release_date: "2021-12-20",
    title: "Movie 3",
    video: true,
    vote_average: 7.0,
    vote_count: 1000,
  },
];
